# Generated by Django 2.2.2 on 2019-09-03 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ReclamaCaicoApp', '0004_auto_20190903_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamacao',
            name='user',
        ),
        migrations.AddField(
            model_name='reclamacao',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
