# Generated by Django 2.2.2 on 2019-09-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReclamaCaicoApp', '0005_auto_20190903_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamacao',
            name='Ncasa',
        ),
        migrations.AlterField(
            model_name='reclamacao',
            name='bairro',
            field=models.CharField(help_text='Digite o Bairro da Reclamacao', max_length=200),
        ),
        migrations.AlterField(
            model_name='reclamacao',
            name='nome',
            field=models.CharField(help_text='Digite o seu nome de usuario', max_length=200),
        ),
        migrations.AlterField(
            model_name='reclamacao',
            name='rua',
            field=models.CharField(help_text='Digite o Rua da Reclamacao', max_length=200),
        ),
        migrations.AlterField(
            model_name='reclamacao',
            name='titulo',
            field=models.CharField(default='w', help_text='Digite o titulo da Reclamacao', max_length=20),
        ),
    ]
