# Generated by Django 2.2.2 on 2019-09-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReclamaCaicoApp', '0006_auto_20190903_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='data',
            field=models.DateField(null=True),
        ),
    ]
