# Generated by Django 2.2.5 on 2019-09-08 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ReclamaCaicoApp', '0011_auto_20190907_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamacao',
            name='curtidas',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Curtida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ReclamaCaicoApp.Reclamacao')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
