# Generated by Django 2.2.5 on 2019-09-08 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReclamaCaicoApp', '0012_auto_20190907_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamacao',
            name='curtidas',
        ),
    ]
