# Generated by Django 2.2.5 on 2019-09-08 04:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ReclamaCaicoApp', '0013_remove_reclamacao_curtidas'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='curtida',
            unique_together={('usuario', 'publicacao')},
        ),
    ]
