# Generated by Django 2.2.5 on 2019-09-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReclamaCaicoApp', '0014_auto_20190908_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamacao',
            name='curtidas',
            field=models.IntegerField(null=True),
        ),
    ]
