# Generated by Django 2.2.4 on 2019-09-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReclamaCaicoApp', '0015_reclamacao_curtidas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamacao',
            name='titulo',
            field=models.CharField(default='w', help_text='Digite o titulo da Reclamacao', max_length=50),
        ),
    ]
