# Generated by Django 2.2.4 on 2019-09-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReclamaCaicoApp', '0017_remove_reclamacao_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamacao',
            name='foto',
            field=models.ImageField(default='w', upload_to='Reclama'),
        ),
    ]
