# Generated by Django 2.2.4 on 2019-09-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReclamaCaicoApp', '0018_reclamacao_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamacao',
            name='foto',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
