# Generated by Django 2.2.4 on 2019-09-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReclamaCaicoApp', '0019_auto_20190909_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamacao',
            name='foto',
            field=models.ImageField(null=True, upload_to='Reclama/'),
        ),
    ]
