# Generated by Django 2.2.4 on 2019-09-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReclamaCaicoApp', '0021_auto_20190909_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamacao',
            name='foto',
            field=models.FileField(null=True, upload_to='Reclama'),
        ),
    ]
