# Generated by Django 2.2.2 on 2019-09-15 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReclamaCaicoApp', '0022_auto_20190909_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamacao',
            name='vencimento',
            field=models.DateField(default=datetime.date(2019, 9, 15)),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='data',
            field=models.DateField(default=datetime.date(2019, 9, 15)),
        ),
        migrations.AlterField(
            model_name='reclamacao',
            name='foto',
            field=models.FileField(null=True, upload_to='Reclamacao'),
        ),
    ]
