# Generated by Django 2.0.4 on 2019-09-17 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReclamaCaicoApp', '0025_auto_20190915_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='data',
            field=models.DateField(default=datetime.date(2019, 9, 17)),
        ),
        migrations.AlterField(
            model_name='reclamacao',
            name='vencimento',
            field=models.DateField(default=datetime.date(2019, 10, 17)),
        ),
    ]
